### ISSUE TITLE
issue-1- user-can-see-which-pokemon-to-name

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/ajax-project#1]
## 💰 Motivation

Once the quiz has started, a user is given an image of a random pokemon for them to guess.

## 📐 Plan

Allows user to view the pokemon at question

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76715055/108919506-f8fa9900-75e7-11eb-845d-dac1bf07f09f.png)

## ✅ Task List

- [x] Add the HTML of the "Name the pokemon" title and a filler section for the pokemon at question
- [x] Style the CSS to make it look nice
- [x] Make a function where it chooses a pokemon ID at random.
- [x] Display the image of that randomly chosen pokemon that comes from the PokeAPI.
- [x] Further style the image to make it fit look alike the title
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
