### ISSUE TITLE
issue-2-user-can-type-their-answer

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/ajax-project#2]
## 💰 Motivation

Under the image of the pokemon will be a text-box where the user can type their answer. If the answer is right it will move on to the next image. If the answer is correct, the textbox will glow green and the user will be asked to try again.

## 📐 Plan

Allows user to type their guess

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76715055/108921418-29900200-75eb-11eb-8f25-e93e6161cfc9.png)

## ✅ Task List

- [x] Create the HTML and CSS for the text box.
- [x] Edit getPokemon function so that it also retrieves the Pokemon's name
- [x] Add an event listener to the text-box that listens for input events from the user.
- [x] Create a function that compares the name the user input with the name of the Pokemon.
- [x] Add the CSS classes to that make the textbox green when correct. 
- [x] When the user submits the right answer go to the next Pokemon.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
