### ISSUE TITLE
issue-3-user-can-skip-the-question

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/ajax-project#3]
## 💰 Motivation

If the user is stuck on a question they can skip that question and it will be added to the end of the list.

## 📐 Plan

Allows user to skip the current pokemon at question

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76715055/108921101-b1294100-75ea-11eb-83b5-779b5e062811.png)

## ✅ Task List

- [x] Add a skip button in HTML and style it accordingly in CSS.
- [x] Make a function for when the user clicks that button, it goes on to the next Pokemon.
- [x] Add an event listener to the button for clicks.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
