### ISSUE TITLE
issue-4-user-can-set-a-time-limit

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/ajax-project#4]
## 💰 Motivation

At the start the user is asked to set how long they would like the quiz to last.

## 📐 Plan

Allows user to set the time duration of the quiz

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76715055/108923444-ae7c1b00-75ed-11eb-86ac-fbf7ecfdc931.png)
![image](https://user-images.githubusercontent.com/76715055/108923198-3d3c6800-75ed-11eb-9851-9e5ad1176cb3.png)

## ✅ Task List

- [x] Add a home screen to the app.
- [x] When the user selects a time, and submits the home screen should disappear and the quiz screen should appear.
- [x] When the quiz screen appears a visible timer should countdown from 5 and then the quiz should start counting down from the specified time.
- [x] Stop the quiz when the time is up(hide the quiz).
- [x] Visibly display the timer on the quiz screen.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
