### ISSUE TITLE
issue-5-user-can-view-their-scores

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/ajax-project#5]
## 💰 Motivation

If the user has a history of completed quizzes, they can view their previous scores from a button on the homescreen.

## 📐 Plan

Allows user to view their previous scores.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76715055/108923171-31e93c80-75ed-11eb-9418-8273734bd384.png)
![image](https://user-images.githubusercontent.com/76715055/108923346-8096d680-75ed-11eb-947b-bbbb750b45f7.png)

## ✅ Task List

- [x] Make the leaderboard tab and style it in CSS.
- [x] Change the time input options to only have 4 options, 1 min, 5min, 10min, and 20min.
- [x] Modify the home page to have a leaderboard button, and when clicked displays the leaderboard screen, and add a home button to the leaderboard tab.
- [x] Create a data structure that organizes the user's scores based on what time they chose and how well they did.
- [x] Edit the getPokemon function and the countDownQuiz function to submit a score once the time runs out, or finished all pokemon.
- [x] Save this data to local storage.
- [x] Once the user has finished the quiz, it should display the respected Leaderboard for their time.
- [x] Display the scores on the leaderboard from highest to lowest, out of 10.
- [x] Add a home button on the leaderboard tag that takes them back to the home page when clicked.
- [x] Edit CSS
